{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>\u0001\u001a\u0001</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ñì\b\u0002Ó°&gt;</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>\u0001\u0001</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>?ý&gt;è&gt;è&gt;ç&gt;à&gt;è&gt;é&gt;Ù&gt;Ê&gt;Ù&gt;Þ&gt;Ì&gt;¸&gt;µ&gt;¼&gt;½&gt;½&gt;¯&gt;´&gt;É&gt;é&gt;í&gt;Ü...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>?í&gt;¨&gt;x&gt;R&gt;]&gt;`&gt;X&gt;M&gt;l&gt;B&gt;7&gt;&gt;Ã&gt;Ó&gt;ù&gt;ÿ&gt;ü&gt;ú&gt;ó&gt;ù&gt;</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4373</th>\n",
       "      <td>?</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4374</th>\n",
       "      <td>=û&lt;$=u= =ä=\u0013&gt;\u001b&gt;$&gt;ö=Ë=³=¦=¸==ª=ÿ==q&lt;&lt;\\=\u0005&gt;¨=G...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4375</th>\n",
       "      <td>&gt;ß=à==­&lt;;Ç:Õ:\u000e;6;¯;ç;\u001c&lt;</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4376</th>\n",
       "      <td>&lt;;Ú;&lt;&lt;v&lt;Þ&lt;Ê&lt;¨&lt;¾&lt;j=R=x&lt;P&lt;4&lt;Ð;æ;&lt;©&lt;e&lt;M&lt;&lt;&lt;\u0007...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4377</th>\n",
       "      <td>&gt;Ì==±=\u0013&gt;¾&gt;\"?\u0018?¨&gt;R&gt;ò&gt;¡?Ò?Ï?Ð?Ô?Õ?×?Õ?Ø?Ú?Ø?Ù?Ý...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>4378 rows × 1 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                   \u0001\u001a\u0001\n",
       "\n",
       "0                                               Ñì\b\u0002Ó°>\n",
       "1                                                    \u0001\u0001\n",
       "2                                                     /\n",
       "3     ?ý>è>è>ç>à>è>é>Ù>Ê>Ù>Þ>Ì>¸>µ>¼>½>½>¯>´>É>é>í>Ü...\n",
       "4             ?í>¨>x>R>]>`>X>M>l>B>7>>Ã>Ó>ù>ÿ>ü>ú>ó>ù>\n",
       "...                                                 ...\n",
       "4373                                                  ?\n",
       "4374  =û<$=u= =ä=\u0013>\u001b>$>ö=Ë=³=¦=¸==ª=ÿ==q<<\\=\u0005>¨=G...\n",
       "4375                          >ß=à==­<;Ç:Õ:\u000e;6;¯;ç;\n",
       "<\n",
       "4376  <;Ú;\n",
       "<<v<Þ<Ê<¨<¾<j=R=x<P<4<Ð;æ;<©<e<M<<<\u0007...\n",
       "4377  >Ì==±=\u0013>¾>\"?\u0018?¨>R>ò>¡?Ò?Ï?Ð?Ô?Õ?×?Õ?Ø?Ú?Ø?Ù?Ý...\n",
       "\n",
       "[4378 rows x 1 columns]"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import os\n",
    "\n",
    "os.chdir('C:/Users/natha/Desktop/Thesis/Storm_Database/VONGFONG/2020051118/MyDocuments/')\n",
    "\n",
    "df = pd.read_csv('HS_H08_20200511_1800_B07_FLDK_R20_S0110.DAT', encoding= 'unicode_escape', on_bad_lines='skip')\n",
    "df\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n",
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n"
     ]
    }
   ],
   "source": [
    "from satpy import Scene, MultiScene \n",
    "import glob as glob\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_12/00/')\n",
    "\n",
    "lat = 16.4\n",
    "lon = 119.4\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn1 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn1.load(['B07','B11','B13','B14','B15'])\n",
    "mscn2 = mscn1.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn2.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_12/06/')\n",
    "\n",
    "lat = 16.9\n",
    "lon = 118.2\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn2 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn2.load(['B07','B11','B13','B14','B15'])\n",
    "mscn3 = mscn2.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn3.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_12/12/')\n",
    "\n",
    "lat = 17.4\n",
    "lon = 117.2\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn3 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn3.load(['B07','B11','B13','B14','B15'])\n",
    "mscn4 = mscn3.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn4.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_12/18/')\n",
    "\n",
    "lat = 17.9\n",
    "lon = 116.2\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn4 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn4.load(['B07','B11','B13','B14','B15'])\n",
    "mscn5 = mscn4.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn5.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_13/00/')\n",
    "\n",
    "lat = 18.5\n",
    "lon = 115.4\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn5 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn5.load(['B07','B11','B13','B14','B15'])\n",
    "mscn6 = mscn5.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn6.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_13/06/')\n",
    "\n",
    "lat = 19.2\n",
    "lon = 114.6\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn6 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn6.load(['B07','B11','B13','B14','B15'])\n",
    "mscn7 = mscn6.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn7.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_13/12/')\n",
    "\n",
    "lat = 19.9\n",
    "lon = 113.9\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn7 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn7.load(['B07','B11','B13','B14','B15'])\n",
    "mscn8 = mscn7.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn8.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_13/18/')\n",
    "\n",
    "lat = 20.7\n",
    "lon = 113.1\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn8 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn8.load(['B07','B11','B13','B14','B15'])\n",
    "mscn9 = mscn8.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn9.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_14/00/')\n",
    "\n",
    "lat = 21.4\n",
    "lon = 112.2\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn9 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn9.load(['B07','B11','B13','B14','B15'])\n",
    "mscn10 = mscn9.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn10.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_14/06/')\n",
    "\n",
    "lat = 22.2\n",
    "lon = 111.3\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "mscn10 = MultiScene.from_files(glob.glob('*.DAT'), reader='ahi_hsd')\n",
    "mscn10.load(['B07','B11','B13','B14','B15'])\n",
    "mscn11 = mscn10.crop(ll_bbox=bbox)\n",
    "\n",
    "mscn11.save_datasets(writer='cf', base_dir = 'D:/Thesis/Nuri/Cropped/')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Users\\natha\\anaconda3\\envs\\metpy1\\lib\\site-packages\\dask\\core.py:119: RuntimeWarning: invalid value encountered in log\n",
      "  return func(*(_execute_task(a, cache) for a in args))\n"
     ]
    }
   ],
   "source": [
    "from satpy import Scene, MultiScene \n",
    "import glob\n",
    "\n",
    "# Best Track Central Lat/Lon\n",
    "\n",
    "lat = 17.9\n",
    "lon = 116.2\n",
    "bbox = (lon+5, lat+5, lon-5, lat-5)\n",
    "\n",
    "# 2020051118\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/06_12/18/TEST3/')\n",
    "\n",
    "scn = Scene(filenames=glob.glob('*.dat'), reader=\"ahi_hsd\")\n",
    "scn.available_dataset_names()\n",
    "scn.load([\"B07\"])\n",
    "scn2 = scn.crop(ll_bbox=bbox)\n",
    "\n",
    "scn2.save_datasets(writer='simple_image', base_dir = 'D:/Thesis/Nuri/TEST/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'netCDF4._netCDF4.Dataset'>\n",
      "root group (NETCDF4 data model, file format HDF5):\n",
      "    history: Created by pytroll/satpy on 2023-07-16 00:39:35.797725\n",
      "    Conventions: CF-1.7\n",
      "    dimensions(sizes): y(517), x(531)\n",
      "    variables(dimensions): int32 FLDK(), float64 y(y), float64 x(x), float64 longitude(y, x), float64 latitude(y, x), float32 B07(y, x), float32 B11(y, x), float32 B13(y, x), float32 B14(y, x), float32 B15(y, x)\n",
      "    groups: \n"
     ]
    }
   ],
   "source": [
    "import netCDF4\n",
    "import os\n",
    "\n",
    "os.chdir('D:/Thesis/Nuri/Cropped/')\n",
    "file2read = netCDF4.Dataset('B14_20200612_022000.nc','r')\n",
    "print(file2read)\n",
    "file2read.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "metpy1",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
